site_name: Moonbeam Docs
site_url: https://docs.moonbeam.network
site_dir: /var/www/moonbeam-docs-static
docs_dir: moonbeam-docs
copyright: © 2020 PureStake, Inc. All Rights Reserved. 
#repo_name: PureStake/moonbeam-docs
#repo_url: https://github.com/PureStake/moonbeam-docs
#edit_uri: ""
theme: 
  name: material
  custom_dir: material-overrides
  favicon: /assets/images/Moonbeam-Favicon-50.png
  logo:  /assets/images/Moonbeam-Favicon-50.png
  font:
    text: Open Sans
markdown_extensions:
  - codehilite
  - meta
  - toc:
      permalink: true
      title: Sections
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - material-overrides/.icons
plugins:
  - search
  - awesome-pages
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MoonbeamNetwork
      name: Twitter
    - icon: moonbeam/element
      link: https://riot.im/app/#/room/!dzULkAiPePEaverEEP:matrix.org?via=matrix.org
      name: Element (Riot)
    - icon: fontawesome/brands/telegram-plane
      link: https://t.me/Moonbeam_Official
      name: Telegram
    - icon: fontawesome/solid/envelope
      link: https://moonbeam.network/newsletter/ 
      name: Email Newsletter
    - icon: fontawesome/brands/github
      link: https://github.com/PureStake/moonbeam
      name: GitHub
google_analytics:
  - UA-135971059-6
  - auto