site_name: Moonbeam Docs
site_url: https://docs.moonbeam.network
home_url: https://moonbeam.network
site_dir: /var/www/moonbeam-docs-static
docs_dir: moonbeam-docs
copyright: © 2020 PureStake, Inc. All Rights Reserved. 
#repo_name: PureStake/moonbeam-docs
#repo_url: https://github.com/PureStake/moonbeam-docs
#edit_uri: ""
theme: 
  name: material
  custom_dir: material-overrides
  favicon: /assets/images/Moonbeam-Favicon-50.png
  logo:  /assets/images/Moonbeam-Favicon-50.png
  font:
    text: Open Sans
markdown_extensions:
  - codehilite
  - meta
  - toc:
      permalink: true
      title: Sections
  - admonition
  - pymdownx.snippets:
      base_path: moonbeam-docs/code-snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - material-overrides/.icons
plugins:
  - search
  - awesome-pages
  - redirects:
      redirect_maps:
        'resources/networks.md': 'networks/overview.md'
        'getting-started/setting-up-a-node.md': 'getting-started/local-node/setting-up-a-node.md'
        'getting-started/using-metamask.md': 'getting-started/local-node/using-metamask.md'
        'getting-started/using-remix.md': 'getting-started/local-node/using-remix.md'
        'getting-started/using-truffle.md': 'getting-started/local-node/using-truffle.md'
        'getting-started/web3-transaction.md': 'getting-started/local-node/web3-transaction.md'
        'getting-started/web3-contract.md': 'getting-started/local-node/web3-contract.md'
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MoonbeamNetwork
      name: Twitter
    - icon: fontawesome/brands/discord
      link: https://discord.gg/PfpUATX
      name: Discord
    - icon: moonbeam/element
      link: https://app.element.io/#/room/#moonbeam:matrix.org
      name: Element (Riot)
    - icon: fontawesome/brands/telegram-plane
      link: https://t.me/Moonbeam_Official
      name: Telegram
    - icon: fontawesome/solid/envelope
      link: https://moonbeam.network/newsletter/ 
      name: Email Newsletter
    - icon: fontawesome/brands/github
      link: https://github.com/PureStake/moonbeam
      name: GitHub
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/MoonbeamNetwork
      name: YouTube
google_analytics:
  - UA-135971059-6
  - auto
