site_name: Moonbeam Docs
site_url: https://docs.moonbeam.network/
home_url: https://moonbeam.network/
site_dir: /var/www/moonbeam-docs-static
docs_dir: moonbeam-docs
copyright: © 2024 Moonbeam Foundation. All Rights Reserved.
extra_javascript:
  - js/connectMetaMask.js
  - js/errorModal.js
  - js/networkModal.js
  - js/handleLanguageChange.js
  - js/fixCreatedDate.js
  - js/externalLinkModal.js
extra_css:
  - /assets/stylesheets/moonbeam.css
  - /assets/stylesheets/termynal.css
theme:
  name: material
  custom_dir: material-overrides
  favicon: /assets/images/favicon.webp
  logo: /assets/images/logo.webp
  font:
    text: Banana Grotesk
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - content.code.copy
    - announce.dismiss
markdown_extensions:
  - codehilite
  - meta
  - toc:
      permalink: true
      title: Sections
  - admonition
  - pymdownx.snippets:
      base_path: moonbeam-docs/.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - material-overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
validation:
  absolute_links: ignore
  unrecognized_links: ignore
exclude_docs: README.md
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      exclude:
        - .snippets/*
      enabled: !ENV ENABLED_GIT_REVISION_DATE, True
      enable_creation_date: true
  # - privacy
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      js_files:
        - js/connectMetaMask.js
        - js/errorModal.js
        - js/networkModal.js
        - js/handleLanguageChange.js
        - js/fixCreatedDate.js
        - js/externalLinkModal.js
      css_files:
        - /assets/stylesheets/termynal.css
        - /assets/stylesheets/moonbeam.css
  - redirects:
      redirect_maps:
        builders/build/canonical-contracts/precompiles/eth-mainnet.md: builders/ethereum/precompiles/utility/eth-mainnet.md
        builders/build/eth-api/debug-trace.md: builders/ethereum/json-rpc/debug-trace.md
        builders/build/eth-api/dev-env/truffle.md: builders/ethereum/dev-env/index.md
        builders/build/eth-api/pubsub.md: builders/ethereum/json-rpc/pubsub.md
        builders/build/moonbeam-custom-api.md: builders/ethereum/json-rpc/moonbeam-custom-api.md
        builders/get-started/eth-compare/index.md: learn/core-concepts/index.md
        builders/get-started/eth-compare/balances.md: learn/core-concepts/balances.md
        builders/get-started/eth-compare/consensus-finality.md: learn/core-concepts/consensus-finality.md
        builders/get-started/eth-compare/rpc-support.md: builders/ethereum/json-rpc/eth-rpc.md
        builders/get-started/eth-compare/security.md: learn/core-concepts/security.md
        builders/get-started/eth-compare/transfers-api.md: learn/core-concepts/transfers-api.md
        builders/get-started/eth-compare/tx-fees.md: learn/core-concepts/tx-fees.md
        builders/get-started/moonbase.md: builders/get-started/networks/moonbase.md
        builders/get-started/moonriver.md: builders/get-started/networks/moonriver.md
        builders/get-started/moonbeam.md: builders/get-started/networks/moonbeam.md
        builders/get-started/networks/layer2/bobabeam.md: builders/get-started/networks/index.md
        builders/interact/hardhat.md: builders/ethereum/dev-env/hardhat.md
        builders/interoperability/xcm/xc20/xtokens.md: builders/interoperability/xcm/xc20/send-xc20s/index.md
        builders/interoperability/xcm/fees.md: builders/interoperability/xcm/core-concepts/weights-fees.md
        builders/interoperability/xcm/remote-evm-calls.md: builders/interoperability/xcm/remote-execution/remote-evm-calls.md
        builders/interoperability/xcm/xc20/mintable-xc20.md: builders/interoperability/xcm/xc20/overview.md
        builders/interoperability/xcm/xcm-transactor.md: builders/interoperability/xcm/remote-execution/substrate-calls/index.md
        builders/interoperability/xcm/xc-integration.md: builders/interoperability/xcm/xc-registration/index.md
        builders/pallets-precompiles/precompiles/xcm-utils.md: builders/interoperability/xcm/xcm-utils.md
        builders/xcm/fees.md: builders/interoperability/xcm/core-concepts/weights-fees.md
        builders/xcm/xc20/index.md: builders/interoperability/xcm/xc20/index.md
        builders/xcm/xc20/overview.md: builders/interoperability/xcm/xc20/overview.md
        builders/xcm/xc20/xtokens.md: builders/interoperability/xcm/xc20/send-xc20s/index.md
        builders/xcm/xcm-sdk/xcm-sdk.md: https://moonbeam-foundation.github.io/xcm-sdk/latest/
        builders/xcm/xcm-transactor.md: builders/interoperability/xcm/remote-execution/substrate-calls/index.md
        builders/xcm/xc-integration.md: builders/interoperability/xcm/xc-registration/index.md
        getting-started/using-metamask.md: tokens/connect/metamask.md
        getting-started/using-remix.md: builders/ethereum/dev-env/remix.md
        getting-started/using-truffle.md: builders/ethereum/dev-env/index.md
        getting-started/local-node/deploy-contract.md: builders/ethereum/libraries/index.md
        getting-started/local-node/using-remix.md: builders/ethereum/dev-env/remix.md
        getting-started/local-node/web3-transaction.md: builders/ethereum/libraries/web3py.md
        getting-started/moonriver/integrate-metamask.md: builders/get-started/networks/moonriver.md
        getting-started/testnet/faucet.md: builders/get-started/networks/moonbase.md
        getting-started/testnet/metamask.md: tokens/connect/metamask.md
        getting-started/testnet/precompiles.md: builders/ethereum/precompiles/index.md
        getting-started/testnet/pubsub.md: builders/ethereum/json-rpc/pubsub.md
        integrations/openzeppelin/overview.md: builders/ethereum/dev-env/openzeppelin/overview.md
        learn/dapps-list/dtmb.md: learn/dapps-list/index.md
        learn/features/unified-accounts.md: learn/core-concepts/unified-accounts.md
        learn/platform/roadmap.md: index.md
        learn/unified-accounts.md: learn/core-concepts/unified-accounts.md
        networks/moonriver.md: learn/platform/networks/moonriver.md
        node-operators/networks/full-node.md: node-operators/networks/run-a-node/overview.md
        tutorials/eth-api/truffle-start-to-end.md: tutorials/eth-api/get-started.index.md
        builders/build/index.md: builders/ethereum/index.md
        builders/build/canonical-contracts.md: builders/ethereum/canonical-contracts.md
        builders/build/eth-api/dev-env/ape.md: builders/ethereum/dev-env/ape.md
        builders/build/eth-api/dev-env/brownie.md: builders/ethereum/dev-env/brownie.md
        builders/build/eth-api/dev-env/foundry.md: builders/ethereum/dev-env/foundry.md
        builders/build/eth-api/dev-env/hardhat.md: builders/ethereum/dev-env/hardhat.md
        builders/build/eth-api/dev-env/index.md: builders/ethereum/dev-env/index.md
        builders/build/eth-api/dev-env/openzeppelin/contracts.md: builders/ethereum/dev-env/openzeppelin/contracts.md
        builders/build/eth-api/dev-env/openzeppelin/defender.md: builders/ethereum/dev-env/openzeppelin/defender.md
        builders/build/eth-api/dev-env/openzeppelin/index.md: builders/ethereum/dev-env/openzeppelin/index.md
        builders/build/eth-api/dev-env/openzeppelin/overview.md: builders/ethereum/dev-env/openzeppelin/overview.md
        builders/build/eth-api/dev-env/remix.md: builders/ethereum/dev-env/remix.md
        builders/build/eth-api/dev-env/scaffold-eth.md: builders/ethereum/dev-env/scaffold-eth.md
        builders/build/eth-api/dev-env/tenderly.md: builders/ethereum/dev-env/tenderly.md
        builders/build/eth-api/dev-env/thirdweb.md: builders/ethereum/dev-env/thirdweb.md
        builders/build/eth-api/dev-env/waffle-mars.md: builders/ethereum/dev-env/waffle-mars.md
        builders/build/eth-api/index.md: builders/ethereum/index.md
        builders/ethereum/historical-updates.md: builders/build/historical-updates.md
        builders/ethereum/runtime-upgrades.md: builders/build/runtime-upgrades.md
        builders/json-rpc/debug-trace.md: builders/ethereum/json-rpc/debug-trace.md
        builders/json-rpc/eth-rpc.md: builders/ethereum/json-rpc/eth-rpc.md
        builders/json-rpc/index.md: builders/ethereum/json-rpc/index.md
        builders/json-rpc/moonbeam-custom-api.md: builders/ethereum/json-rpc/moonbeam-custom-api.md
        builders/json-rpc/pubsub.md: builders/ethereum/json-rpc/pubsub.md
        builders/build/eth-api/libraries/ethersjs.md: builders/ethereum/libraries/ethersjs.md
        builders/build/eth-api/libraries/ethersrs.md: builders/ethereum/libraries/ethersrs.md
        builders/build/eth-api/libraries/index.md: builders/ethereum/libraries/index.md
        builders/build/eth-api/libraries/viem.md: builders/ethereum/libraries/viem.md
        builders/build/eth-api/libraries/web3js.md: builders/ethereum/libraries/web3js.md
        builders/build/eth-api/libraries/web3py.md: builders/ethereum/libraries/web3py.md
        builders/pallets-precompiles/precompiles/identity.md: builders/ethereum/precompiles/account/identity.md
        builders/pallets-precompiles/precompiles/proxy.md: builders/ethereum/precompiles/account/proxy.md
        builders/pallets-precompiles/precompiles/collective.md: builders/ethereum/precompiles/features/governance/collective.md
        builders/pallets-precompiles/precompiles/conviction-voting.md: builders/ethereum/precompiles/features/governance/conviction-voting.md
        builders/pallets-precompiles/precompiles/preimage.md: builders/ethereum/precompiles/features/governance/preimage.md
        builders/pallets-precompiles/precompiles/referenda.md: builders/ethereum/precompiles/features/governance/referenda.md
        builders/pallets-precompiles/precompiles/randomness.md: builders/ethereum/precompiles/features/randomness.md
        builders/pallets-precompiles/precompiles/staking.md: builders/ethereum/precompiles/features/staking.md
        builders/pallets-precompiles/precompiles/index.md: builders/ethereum/precompiles/index.md
        builders/pallets-precompiles/precompiles/gmp.md: builders/ethereum/precompiles/interoperability/gmp.md
        builders/pallets-precompiles/precompiles/overview.md: builders/ethereum/precompiles/overview.md
        builders/pallets-precompiles/precompiles/eth-mainnet.md: builders/ethereum/precompiles/utility/eth-mainnet.md
        builders/pallets-precompiles/precompiles/registry.md: builders/ethereum/precompiles/utility/registry.md
        builders/pallets-precompiles/precompiles/relay-data-verifier.md: builders/ethereum/precompiles/utility/relay-data-verifier.md
        builders/pallets-precompiles/precompiles/batch.md: builders/ethereum/precompiles/ux/batch.md
        builders/pallets-precompiles/precompiles/call-permit.md: builders/ethereum/precompiles/ux/call-permit.md
        builders/pallets-precompiles/precompiles/erc20.md: builders/ethereum/precompiles/ux/erc20.md
        builders/build/eth-api/verify-contracts/api-verification.md: builders/ethereum/verify-contracts/api-verification.md
        builders/build/eth-api/verify-contracts/block-explorers.md: builders/ethereum/verify-contracts/block-explorers.md
        builders/build/eth-api/verify-contracts/etherscan-plugins.md: builders/ethereum/verify-contracts/etherscan-plugins.md
        builders/build/eth-api/verify-contracts/index.md: builders/ethereum/verify-contracts/index.md
        builders/pallets-precompiles/index.md: index.md
        builders/build/substrate-api/chopsticks.md: builders/substrate/dev-env/chopsticks.md
        builders/build/substrate-api/index.md: builders/substrate/index.md
        builders/pallets-precompiles/pallets/identity.md: builders/substrate/interfaces/account/identity.md
        builders/pallets-precompiles/pallets/multisig.md: builders/substrate/interfaces/account/multisig.md
        builders/pallets-precompiles/pallets/proxy.md: builders/substrate/interfaces/account/proxy.md
        builders/pallets-precompiles/pallets/conviction-voting.md: builders/substrate/interfaces/features/governance/conviction-voting.md
        builders/pallets-precompiles/pallets/preimage.md: builders/substrate/interfaces/features/governance/preimage.md
        builders/pallets-precompiles/pallets/referenda.md: builders/substrate/interfaces/features/governance/referenda.md
        builders/pallets-precompiles/pallets/randomness.md: builders/substrate/interfaces/features/randomness.md
        builders/pallets-precompiles/pallets/staking.md: builders/substrate/interfaces/features/staking.md
        builders/pallets-precompiles/pallets/index.md: builders/substrate/interfaces/index.md
        builders/pallets-precompiles/pallets/utility.md: builders/substrate/interfaces/utility/utility.md
        builders/build/substrate-api/polkadot-js-api.md: builders/substrate/libraries/polkadot-js-api.md
        builders/build/substrate-api/py-substrate-interface.md: builders/substrate/libraries/py-substrate-interface.md
        builders/build/substrate-api/sidecar.md: builders/substrate/libraries/sidecar.md
        builders/build/substrate-api/overview.md: builders/substrate/overview.md
        learn/dapps-list/state-of-the-dapps.md: learn/dapps-list/index.md
        builders/interoperability/xcm/xcm-sdk/index.md: https://moonbeam-foundation.github.io/xcm-sdk/latest/
        builders/interoperability/xcm/xcm-sdk/v0/index.md: https://moonbeam-foundation.github.io/xcm-sdk/v0/
        builders/interoperability/xcm/xcm-sdk/v0/reference.md: https://moonbeam-foundation.github.io/xcm-sdk/v0/reference/interfaces/
        builders/interoperability/xcm/xcm-sdk/v0/xcm-sdk.md: https://moonbeam-foundation.github.io/xcm-sdk/v0/example-usage/
        builders/interoperability/xcm/xcm-sdk/v1/index.md: https://moonbeam-foundation.github.io/xcm-sdk/v1/
        builders/interoperability/xcm/xcm-sdk/v1/reference.md: https://moonbeam-foundation.github.io/xcm-sdk/v1/reference/interfaces/
        builders/interoperability/xcm/xcm-sdk/v1/xcm-sdk.md: https://moonbeam-foundation.github.io/xcm-sdk/v1/example-usage/
        builders/interoperability/xcm/xc20/send-xc20s/xtokens-pallet.md: builders/interoperability/xcm/xc20/send-xc20s/xcm-pallet.md
  - macros:
      include_yaml:
        - moonbeam-docs/variables.yml
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/PfpUATX
      name: Discord
    - icon: fontawesome/brands/telegram
      link: https://t.me/Moonbeam_Official
      name: Telegram
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/MoonbeamNetwork
      name: Twitter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/MoonbeamNetwork
      name: YouTube
    - icon: fontawesome/brands/github
      link: https://github.com/moonbeam-foundation/moonbeam
      name: GitHub
  analytics:
    provider: google
    property: G-5ZBERCXWC3
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up
          label: Yes
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down
          label: No
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by submitting
            <a href="https://github.com/moonbeam-foundation/moonbeam-docs/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">additional feedback</a>.
