'site_name': 'Moonbeam Docs'
'site_url': 'https://docs.moonbeam.network/'
'home_url': 'https://moonbeam.network/'
'site_dir': '/var/www/moonbeam-docs-static'
'docs_dir': 'moonbeam-docs'
'copyright': '© 2023 Moonbeam Foundation. All Rights Reserved.'
'extra_javascript':
  - 'js/connectMetaMask.js'
  - 'js/errorModal.js'
  - 'js/networkModal.js'
  - 'js/handleLanguageChange.js'
  - 'js/fixCreatedDate.js'
  - 'js/externalLinkModal.js'
  - 'https://widget.kapa.ai/kapa-widget.bundle.js'
  - 'js/initKapaWidget.js'
'theme':
  'name': 'material'
  'custom_dir': 'material-overrides'
  'favicon': '/assets/images/Moonbeam-Favicon-50.png'
  'logo': '/assets/images/moonbeam-logo.png'
  'font':
    'text': 'Open Sans'
  'features':
    - 'navigation.tabs'
    - 'navigation.tabs.sticky'
    - 'navigation.sections'
    - 'navigation.indexes'
    - 'navigation.instant'
    - 'content.code.copy'
'markdown_extensions':
  - 'codehilite'
  - 'meta'
  - 'toc':
      'permalink': !!bool 'true'
      'title': 'Sections'
  - 'admonition'
  - 'pymdownx.snippets':
      'base_path': 'moonbeam-docs/.snippets'
  - 'pymdownx.emoji':
      'emoji_index': !!python/name:materialx.emoji.twemoji
      'emoji_generator': !!python/name:materialx.emoji.to_svg
      'options':
        'custom_icons':
          - 'material-overrides/.icons'
  - 'pymdownx.tabbed':
      'alternate_style': !!bool 'true'
  - 'pymdownx.superfences'
  - 'pymdownx.details'
  - 'attr_list'
'validation':
  'absolute_links': 'ignore'
  'unrecognized_links': 'ignore'
'exclude_docs': 'README.md'
'plugins':
  - 'search'
  - 'awesome-pages'
  - 'git-revision-date-localized':
      'exclude':
        - '.snippets/*'
      'enable_creation_date': !!bool 'true'
  - 'redirects':
      'redirect_maps':
        'builders/build/canonical-contracts/precompiles/eth-mainnet.md': 'builders/pallets-precompiles/precompiles/eth-mainnet.md'
        'builders/build/eth-api/dev-env/truffle.md': 'builders/build/eth-api/dev-env/index.md'
        'builders/get-started/moonbase.md': 'builders/get-started/networks/moonbase.md'
        'builders/get-started/moonriver.md': 'builders/get-started/networks/moonriver.md'
        'builders/get-started/moonbeam.md': 'builders/get-started/networks/moonbeam.md'
        'builders/get-started/networks/layer2/bobabeam.md': 'builders/get-started/networks/index.md'
        'builders/interact/hardhat.md': 'builders/build/eth-api/dev-env/hardhat.md'
        'builders/interoperability/xcm/xc-integration.md': 'builders/interoperability/xcm/xc-registration/index.md'
        'builders/xcm/fees.md': 'builders/interoperability/xcm/fees.md'
        'builders/xcm/xc20/index.md': 'builders/interoperability/xcm/xc20/index.md'
        'builders/xcm/xc20/overview.md': 'builders/interoperability/xcm/xc20/overview.md'
        'builders/xcm/xc20/xtokens.md': 'builders/interoperability/xcm/xc20/xtokens.md'
        'builders/xcm/xcm-sdk/xcm-sdk.md': 'builders/interoperability/xcm/xcm-sdk/v1/xcm-sdk.md'
        'builders/xcm/xcm-transactor.md': 'builders/interoperability/xcm/xcm-transactor.md'
        'builders/xcm/xc-integration.md': 'builders/interoperability/xcm/xc-registration/index.md'
        'getting-started/using-metamask.md': 'tokens/connect/metamask.md'
        'getting-started/using-remix.md': 'builders/build/eth-api/dev-env/remix.md'
        'getting-started/using-truffle.md': 'builders/build/eth-api/dev-env/truffle.md'
        'getting-started/local-node/deploy-contract.md': 'builders/build/eth-api/libraries/index.md'
        'getting-started/local-node/using-remix.md': 'builders/build/eth-api/dev-env/remix.md'
        'getting-started/local-node/web3-transaction.md': 'builders/build/eth-api/libraries/web3py.md'
        'getting-started/moonriver/integrate-metamask.md': 'builders/get-started/networks/moonriver.md'
        'getting-started/testnet/faucet.md': 'builders/get-started/networks/moonbase.md'
        'getting-started/testnet/metamask.md': 'tokens/connect/metamask.md'
        'getting-started/testnet/precompiles.md': 'builders/pallets-precompiles/precompiles/index.md'
        'getting-started/testnet/pubsub.md': 'builders/build/eth-api/pubsub.md'
        'integrations/openzeppelin/overview.md': 'builders/build/eth-api/dev-env/openzeppelin/overview.md'
        'learn/platform/roadmap.md': 'index.md'
        'learn/unified-accounts.md': 'learn/features/unified-accounts.md'
        'networks/moonriver.md': 'learn/platform/networks/moonriver.md'
        'node-operators/networks/full-node.md': 'node-operators/networks/run-a-node/overview.md'
        'tutorials/eth-api/truffle-start-to-end.md': 'tutorials/eth-api/get-started.index.md'
  - 'macros':
      'include_yaml':
        - 'moonbeam-docs/variables.yml'
'extra':
  'social':
    - 'icon': 'fontawesome/brands/discord'
      'link': 'https://discord.gg/PfpUATX'
      'name': 'Discord'
    - 'icon': 'moonbeam/element'
      'link': 'https://app.element.io/#/room/#moonbeam:matrix.org'
      'name': 'Element (Riot)'
    - 'icon': 'fontawesome/brands/telegram'
      'link': 'https://t.me/Moonbeam_Official'
      'name': 'Telegram'
    - 'icon': 'fontawesome/brands/twitter'
      'link': 'https://twitter.com/MoonbeamNetwork'
      'name': 'Twitter'
    - 'icon': 'fontawesome/brands/youtube'
      'link': 'https://www.youtube.com/c/MoonbeamNetwork'
      'name': 'YouTube'
    - 'icon': 'fontawesome/brands/github'
      'link': 'https://github.com/moonbeam-foundation/moonbeam'
      'name': 'GitHub'
  'analytics':
    'provider': 'google'
    'property': 'G-5ZBERCXWC3'
    'feedback':
      'title': 'Was this page helpful?'
      'ratings':
        - 'icon': 'material/thumb-up'
          'label': 'Yes'
          'name': 'This page was helpful'
          'data': 1
          'note': >-
            Thanks for your feedback!
        - 'icon': 'material/thumb-down'
          'label': 'No'
          'name': 'This page could be improved'
          'data': 0
          'note': >-
            Thanks for your feedback! Help us improve this page by submitting
            <a href="https://github.com/moonbeam-foundation/moonbeam-docs/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">additional feedback</a>.
