site_name: Moonbeam Docs
site_url: https://docs.moonbeam.network/cn/
home_url: https://moonbeam.network/
site_dir: /var/www/mkdocs-multi-lang/moonbeam-docs-cn-static
docs_dir: moonbeam-docs-cn
copyright: © 2021 PureStake, Inc. All Rights Reserved.
#repo_name: PureStake/moonbeam-docs
#repo_url: https://github.com/PureStake/moonbeam-docs
#edit_uri: ""
extra_javascript:
  [js/connectMetaMask.js, js/errorModal.js, js/handleLanguageChange.js]
theme:
  name: material
  custom_dir: material-overrides
  favicon: /assets/images/Moonbeam-Favicon-50.png
  logo: /assets/images/Moonbeam-Favicon-50.png
  font:
    text: Open Sans
  language: zh
markdown_extensions:
  - codehilite
  - meta
  - toc:
      permalink: true
      title: Sections
  - admonition
  - pymdownx.snippets:
      base_path: moonbeam-docs-cn/snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - material-overrides/.icons
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - attr_list

plugins:
  - search
  - awesome-pages
  - redirects:
      redirect_maps:
        'resources/networks.md': 'networks/overview.md'
        'getting-started/setting-up-a-node.md': 'getting-started/local-node/setting-up-a-node.md'
        'getting-started/using-metamask.md': 'getting-started/local-node/using-metamask.md'
        'getting-started/using-remix.md': 'getting-started/local-node/using-remix.md'
        'getting-started/using-truffle.md': 'getting-started/local-node/using-truffle.md'
        'getting-started/web3-transaction.md': 'getting-started/local-node/send-transaction.md'
        'getting-started/web3-contract.md': 'getting-started/local-node/deploy-contract.md'
        'getting-started/local-node/web3-transaction.md': 'getting-started/local-node/send-transaction.md'
        'getting-started/local-node/ethers-transaction.md': 'getting-started/local-node/send-transaction.md'
        'getting-started/local-node/web3-contract.md': 'getting-started/local-node/deploy-contract.md'
        'getting-started/local-node/ethers-contract.md': 'getting-started/local-node/deploy-contract.md'
        'getting-started/local-node/web3-js/web3-transaction.md': 'getting-started/local-node/send-transaction.md'
        'getting-started/local-node/web3-js/web3-contract.md': 'getting-started/local-node/deploy-contract.md'
        'getting-started/local-node/ethers-js/ethers-transaction.md': 'getting-started/local-node/send-transaction.md'
        'getting-started/local-node/ethers-js/ethers-contract.md': 'getting-started/local-node/deploy-contract.md'
        'getting-started/testnet/pubsub.md': 'integrations/pubsub.md'
        'getting-started/testnet/precompiles.md': 'integrations/precompiles.md'
        'getting-started/testnet/connect.md': 'getting-started/moonbase/connect.md'
        'getting-started/testnet/metamask.md': 'getting-started/moonbase/metamask.md'
        'getting-started/testnet/faucet.md': 'getting-started/moonbase/faucet.md'
        'integrations/metamask.md': 'integrations/wallets/metamask.md'
        'integrations/polkadotjs.md': 'integrations/wallets/polkadotjs.md'
        'integrations/jslibraries/web3js.md': 'integrations/ethlibraries/web3js.md'
        'integrations/jslibraries/etherjs.md': 'integrations/ethlibraries/etherjs.md'
        'networks/testnet.md': 'networks/moonbase.md'
  - macros:
      include_yaml:
        - moonbeam-docs-cn/variables.yml
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/PfpUATX
      name: Discord
    - icon: moonbeam/element
      link: https://app.element.io/#/room/#moonbeam:matrix.org
      name: Element (Riot)
    - icon: fontawesome/brands/telegram-plane
      link: https://t.me/Moonbeam_Official
      name: Telegram
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MoonbeamNetwork
      name: Twitter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/MoonbeamNetwork
      name: YouTube
    - icon: fontawesome/brands/github
      link: https://github.com/PureStake/moonbeam
      name: GitHub
google_analytics:
  - UA-135971059-6
  - auto
