site_name: Moonbeam Docs
site_url: https://docs.moonbeam.network/cn/
home_url: https://moonbeam.network/
site_dir: /var/www/mkdocs-multi-lang/moonbeam-docs-cn-static
docs_dir: moonbeam-docs-cn
'copyright': '© 2021 PureStake, Inc. All Rights Reserved.'
'extra_javascript':
  - 'js/connectMetaMask.js'
  - 'js/errorModal.js'
  - 'js/networkModal.js'
  - 'js/handleLanguageChange.js'
  - 'js/renderSubsections.js'
'theme':
  'name': 'material'
  'custom_dir': 'material-overrides'
  'favicon': '/assets/images/Moonbeam-Favicon-50.png'
  'logo': '/assets/images/Moonbeam-Favicon-50.png'
  'font':
    'text': 'Open Sans'
  'features':
    - 'navigation.tabs'
    - 'navigation.sections'
    - 'navigation.indexes'
'markdown_extensions':
  - 'codehilite'
  - 'meta'
  - 'toc':
      'permalink': !!bool 'true'
      'title': 'Sections'
  - 'admonition'
  - 'pymdownx.snippets':
      'base_path': 'moonbeam-docs-cn/.snippets'
  - 'pymdownx.emoji':
      'emoji_index': !!python/name:materialx.emoji.twemoji
      'emoji_generator': !!python/name:materialx.emoji.to_svg
      'options':
        'custom_icons':
          - 'material-overrides/.icons'
  - 'pymdownx.tabbed'
  - 'pymdownx.superfences'
  - 'pymdownx.details'
  - 'attr_list'
'plugins':
  - 'search'
  - 'awesome-pages'
  - 'section-index'
  - 'redirects':
      'redirect_maps':
        'resources/networks.md': 'learn/platform/networks/overview.md'
        'getting-started/setting-up-a-node.md': 'builders/get-started/networks/moonbeam-dev.md'
        'getting-started/using-metamask.md': 'tokens/connect/metamask.md'
        'getting-started/using-remix.md': 'builders/build/eth-api/dev-env/remix.md'
        'getting-started/using-truffle.md': 'builders/build/eth-api/dev-env/truffle.md'
        'getting-started/web3-transaction.md': 'builders/build/eth-api/libraries/web3py.md'
        'getting-started/web3-contract.md': 'builders/build/eth-api/libraries/web3py.md'
        'getting-started/local-node/web3-transaction.md': 'builders/build/eth-api/libraries/web3py.md'
        'getting-started/local-node/ethers-transaction.md': 'builders/build/eth-api/libraries/ethersjs.md'
        'getting-started/local-node/web3-contract.md': 'builders/build/eth-api/libraries/web3js.md'
        'getting-started/local-node/ethers-contract.md': 'builders/build/eth-api/libraries/ethersjs.md'
        'getting-started/local-node/web3-js/web3-transaction.md': 'builders/build/eth-api/libraries/web3js.md'
        'getting-started/local-node/web3-js/web3-contract.md': 'builders/build/eth-api/libraries/index.md'
        'getting-started/local-node/ethers-js/ethers-transaction.md': 'builders/build/eth-api/libraries/ethersjs.md'
        'getting-started/local-node/ethers-js/ethers-contract.md': 'builders/build/eth-api/libraries/ethersjs.md'
        'getting-started/testnet/pubsub.md': 'builders/build/eth-api/pubsub.md'
        'getting-started/testnet/precompiles.md': 'builders/build/canonical-contracts/precompiles/index.md'
        'builders/tools/precompiles/index.md': 'builders/build/canonical-contracts/precompiles/index.md'
        'getting-started/testnet/connect.md': 'builders/get-started/networks/moonbase.md'
        'getting-started/testnet/metamask.md': 'tokens/connect/metamask.md'
        'getting-started/testnet/faucet.md': 'builders/get-started/networks/moonbase.md'
        'integrations/metamask.md': 'tokens/connect/metamask.md'
        'integrations/polkadotjs.md': 'tokens/connect/polkadotjs.md'
        'integrations/jslibraries/web3js.md': 'builders/build/eth-api/libraries/web3js.md'
        'integrations/jslibraries/etherjs.md': 'builders/build/eth-api/libraries/ethersjs.md'
        'networks/testnet.md': 'learn/platform/networks/moonbase.md'
        'governance/proposals.md': 'tokens/governance/proposals.md'
        'governance/voting.md': 'tokens/governance/voting.md'
        'integrations/indexers/covalent.md': 'builders/integrations/indexers/covalent.md'
        'integrations/indexers/thegraph.md': 'builders/integrations/indexers/thegraph.md'
        'integrations/openzeppelin/defender.md': 'builders/build/eth-api/dev-env/openzeppelin/defender.md'
        'integrations/openzeppelin/overview.md': 'builders/build/eth-api/dev-env/openzeppelin/overview.md'
        'integrations/oracles/band-protocol.md': 'builders/integrations/oracles/band-protocol.md'
        'integrations/oracles/chainlink.md': 'builders/integrations/oracles/chainlink.md'
        'integrations/oracles/razor-network.md': 'builders/integrations/oracles/razor-network.md'
        'networks/moonbase.md': 'learn/platform/networks/moonbase.md'
        'networks/moonriver.md': 'learn/platform/networks/moonriver.md'
        'networks/overview.md': 'learn/platform/networks/overview.md'
        'staking/stake.md': 'tokens/staking/stake.md'
        'staking/stakingprecompile.md': 'builders/build/canonical-contracts/precompiles/staking.md'
        'getting-started/local-node/deploy-contract.md': 'builders/build/eth-api/libraries/index.md'
        'getting-started/local-node/send-transaction.md': 'builders/build/eth-api/libraries/index.md'
        'getting-started/moonbase/metamask.md': 'tokens/connect/metamask.md'
        'integrations/debug-trace.md': 'builders/build/eth-api/debug-trace.md'
        'integrations/ethlibraries/etherjs.md': 'builders/build/eth-api/libraries/ethersjs.md'
        'integrations/ethlibraries/web3js.md': 'builders/build/eth-api/libraries/web3js.md'
        'integrations/ethlibraries/web3py.md': 'builders/build/eth-api/libraries/web3py.md'
        'integrations/explorers.md': 'builders/get-started/explorers.md'
        'builders/tools/explorers/overview.md': 'builders/get-started/explorers.md'
        'builders/tools/explorers/verify-contract.md': 'builders/build/eth-api/verify-contracts/block-explorers.md'
        'integrations/hardhat.md': 'builders/build/eth-api/dev-env/hardhat.md'
        'integrations/precompiles.md': 'builders/build/canonical-contracts/precompiles/index.md'
        'integrations/pubsub.md': 'builders/build/eth-api/pubsub.md'
        'integrations/remix.md': 'builders/build/eth-api/dev-env/remix.md'
        'integrations/waffle-mars.md': 'builders/build/eth-api/dev-env/waffle-mars.md'
        'integrations/wallets/ledger.md': 'tokens/connect/ledger/index.md'
        'integrations/wallets/mathwallet.md': 'tokens/connect/mathwallet.md'
        'integrations/wallets/nifty.md': 'tokens/connect/index.md'
        'tokens/connect/nifty.md': 'tokens/connect/index.md'
        'integrations/wallets/polkadotjs.md': 'tokens/connect/polkadotjs.md'
        'integrations/wallets/trezor.md': 'tokens/connect/trezor.md'
        'learn/consensus.md': 'learn/features/consensus.md'
        'learn/eth-compatibility.md': 'learn/features/eth-compatibility.md'
        'learn/technology.md': 'learn/platform/technology.md'
        'learn/unified-accounts.md': 'learn/features/unified-accounts.md'
        'learn/xchain-plans.md': 'learn/features/xchain-plans.md'
        'learn/dapps-list/list-your-project.md': 'learn/dapps-list/index.md'
        'learn/dapps-list/bridges/index.md': 'learn/dapps-list/index.md'
        'learn/dapps-list/bridges/eth/index.md': 'learn/dapps-list/index.md'
        'learn/dapps-list/bridges/eth/chainbridge.md': 'builders/integrations/bridges/chainbridge.md'
        'builders/integrations/bridges/eth/chainbridge.md': 'builders/integrations/bridges/chainbridge.md'
        'builders/integrations/bridges/eth/index.md': 'builders/integrations/bridges/index.md'
        'learn/dapps-list/defi/index.md': 'learn/dapps-list/index.md'
        'learn/dapps-list/defi/sushiswap.md': 'learn/dapps-list/index.md'
        'learn/dapps-list/defi/amaralend.md': 'learn/dapps-list/index.md'
        'learn/dapps-list/metaTransactions/biconomy.md': 'learn/dapps-list/index.md'
        'learn/dapps-list/metaTransactions/index.md': 'learn/dapps-list/index.md'
        'learn/dapps-list/oracles/dia.md': 'learn/dapps-list/index.md'
        'learn/dapps-list/oracles/chainlink.md': 'builders/integrations/oracles/chainlink.md'
        'learn/dapps-list/template.md': 'learn/dapps-list/index.md'
        'node-operators/indexers/thegraph-node.md': 'node-operators/indexer-nodes/thegraph-node.md'
        'node-operators/oracles/node-chainlink.md': 'node-operators/oracle-nodes/node-chainlink.md'
        'overview/why-polkadot.md': 'learn/platform/why-polkadot.md'
        'resources/code.md': 'learn/platform/code.md'
        'resources/glossary.md': 'learn/platform/glossary.md'
        'resources/links.md': 'learn/platform/links.md'
        'resources/roadmap.md': 'learn/platform/roadmap.md'
        'getting-started/local-node/using-truffle.md': 'builders/build/eth-api/dev-env/truffle.md'
        'integrations/wallets/metamask.md': 'tokens/connect/metamask.md'
        'learn/token.md': 'learn/platform/tokens.md'
        'overview/vision-features.md': 'learn/platform/vision.md'
        'getting-started/local-node/setting-up-a-node.md': 'builders/get-started/networks/moonbeam-dev.md'
        'getting-started/local-node/using-metamask.md': 'tokens/connect/metamask.md'
        'getting-started/local-node/using-remix.md': 'builders/build/eth-api/dev-env/remix.md'
        'getting-started/moonbase/connect.md': 'builders/get-started/networks/moonbase.md'
        'getting-started/moonbase/faucet.md': 'builders/get-started/networks/moonbase.md'
        'getting-started/moonriver/connect.md': 'builders/get-started/networks/moonriver.md'
        'getting-started/moonriver/integrate-metamask.md': 'builders/get-started/networks/moonriver.md'
        'governance/overview.md': 'learn/features/governance.md'
        'integrations/openzeppelin/contracts.md': 'builders/build/eth-api/dev-env/openzeppelin/contracts.md'
        'integrations/trufflebox.md': 'builders/build/eth-api/dev-env/truffle.md'
        'staking/overview.md': 'learn/features/staking.md'
        'treasury/overview.md': 'learn/features/treasury.md'
        'dapps-list/bridges/chainbridge.md': 'builders/integrations/bridges/chainbridge.md'
        'dapps-list/defi/sushiswap.md': 'learn/dapps-list/index.md'
        'dapps-list/metatransactions/biconomy.md': 'learn/dapps-list/index.md'
        'dapps-list/oracles/chainlink.md': 'builders/integrations/oracles/chainlink.md'
        'dapps-list/oracles/dia.md': 'learn/dapps-list/index.md'
        'dapps-list/template.md': 'learn/dapps-list/index.md'
        'builders/interact/metamask-dapp.md': 'builders/integrations/wallets/metamask.md'
        'builders/get-started/api-providers.md': 'builders/get-started/endpoints.md'
        'node-operators/networks/full-node.md': 'node-operators/networks/run-a-node/overview.md'
        'node-operators/networks/compile-binary.md': 'node-operators/networks/run-a-node/systemd.md'
        'builders/tools/openzeppelin/defender.md': 'builders/build/eth-api/dev-env/openzeppelin/defender.md'
        'builders/tools/openzeppelin/overview.md': 'builders/build/eth-api/dev-env/openzeppelin/overview.md'
        'builders/tools/hardhat.md': 'builders/build/eth-api/dev-env/hardhat.md'
        'builders/tools/mars.md': 'builders/build/eth-api/dev-env/waffle-mars.md' 
        'builders/tools/remix.md': 'builders/build/eth-api/dev-env/remix.md'
        'builders/tools/truffle.md': 'builders/build/eth-api/dev-env/truffle.md'
        'builders/tools/waffle.md': 'builders/build/eth-api/dev-env/waffle-mars.md'
        'integrations/bridges/ethereum/chainbridge.md': 'builders/integrations/bridges/chainbridge.md'
        'tokens/staking/stakingprecompile.md': 'builders/build/canonical-contracts/precompiles/staking.md'
        'node-operators/networks/collator.md': 'node-operators/networks/collators/index.md'
        'builders/interact/canonical-contracts.md': 'builders/build/canonical-contracts/contracts.md'
        'builders/tools/precompiles/democracy.md': 'builders/build/canonical-contracts/precompiles/democracy.md'
        'builders/tools/precompiles/erc20.md': 'builders/build/canonical-contracts/precompiles/erc20.md'
        'builders/tools/precompiles/eth-mainnet.md': 'builders/build/canonical-contracts/precompiles/eth-mainnet.md'
        'builders/tools/precompiles/staking.md': 'builders/build/canonical-contracts/precompiles/staking.md'
        'builders/tools/debug-trace.md': 'builders/build/eth-api/debug-trace.md'
        'builders/interact/hardhat.md': 'builders/build/eth-api/dev-env/hardhat.md'
        'builders/tools/eth-dev-env/hardhat.md': 'builders/build/eth-api/dev-env/hardhat.md'
        'builders/tools/eth-dev-env/openzeppelin/defender.md': 'builders/build/eth-api/dev-env/openzeppelin/defender.md'
        'builders/tools/eth-dev-env/openzeppelin/overview.md': 'builders/build/eth-api/dev-env/openzeppelin/overview.md'
        'builders/interact/oz-remix.md': 'builders/build/eth-api/dev-env/openzeppelin/contracts.md'
        'builders/tools/eth-dev-env/remix.md': 'builders/build/eth-api/dev-env/remix.md'
        'builders/interact/remix.md': 'builders/build/eth-api/dev-env/remix.md'
        'builders/interact/truffle.md': 'builders/build/eth-api/dev-env/truffle.md'
        'builders/tools/eth-dev-env/truffle.md': 'builders/build/eth-api/dev-env/truffle.md'
        'builders/interact/waffle-mars.md': 'builders/build/eth-api/dev-env/waffle-mars.md'
        'builders/tools/eth-dev-env/mars.md': 'builders/build/eth-api/dev-env/waffle-mars.md' 
        'builders/tools/eth-dev-env/waffle.md': 'builders/build/eth-api/dev-env/waffle-mars.md' 
        'builders/interact/eth-libraries/deploy-contract.md': 'builders/build/eth-api/libraries/index.md'
        'builders/interact/eth-libraries/send-transaction.md': 'builders/build/eth-api/libraries/index.md'
        'builders/tools/eth-libraries/web3js.md': 'builders/build/eth-api/libraries/web3js.md'
        'builders/tools/eth-libraries/web3py.md': 'builders/build/eth-api/libraries/web3py.md'
        'builders/tools/pubsub.md': 'builders/build/eth-api/pubsub.md'
        'builders/tools/verify-contracts/block-explorers.md': 'builders/build/eth-api/verify-contracts/block-explorers.md'
        'builders/tools/verify-contracts/etherscan-plugins.md': 'builders/build/eth-api/verify-contracts/etherscan-plugins.md'
        'builders/tools/sidecar.md': 'builders/build/substrate-api/sidecar.md'
        'builders/tools/explorers.md': 'builders/get-started/explorers.md'
        'builders/get-started/moonbase.md': 'builders/get-started/networks/moonbase.md'
        'builders/get-started/moonriver.md': 'builders/get-started/networks/moonriver.md'
        'builders/get-started/moonbeam.md': 'builders/get-started/networks/moonbeam.md'
        'builders/get-started/moonbeam-dev.md': 'builders/get-started/networks/moonbeam-dev.md'
        'builders/tools/wallets/metamask.md': 'builders/integrations/wallets/metamask.md'
        'builders/tools/wallets/walletconnect.md': 'builders/integrations/wallets/walletconnect.md'
        'builders/interact/identity.md': 'tokens/manage/identity.md'
        'builders/tools/multisig-safe.md': 'tokens/manage/multisig-safe.md'
        'builders/interact/proxy-accounts.md': 'tokens/manage/proxy-accounts.md'
        'builders/tools/eth-libraries/etherjs.md': 'builders/build/eth-api/libraries/ethersjs.md'
        'builders/interact/scaffold-eth.md': 'builders/build/eth-api/dev-env/scaffold-eth.md'
  - 'macros':
      'include_yaml':
        - 'moonbeam-docs-cn/variables.yml'
'extra':
  'social':
    - 'icon': 'fontawesome/brands/discord'
      'link': 'https://discord.gg/PfpUATX'
      'name': 'Discord'
    - 'icon': 'moonbeam/element'
      'link': 'https://app.element.io/#/room/#moonbeam:matrix.org'
      'name': 'Element (Riot)'
    - 'icon': 'fontawesome/brands/telegram-plane'
      'link': 'https://t.me/Moonbeam_Official'
      'name': 'Telegram'
    - 'icon': 'fontawesome/brands/twitter'
      'link': 'https://twitter.com/MoonbeamNetwork'
      'name': 'Twitter'
    - 'icon': 'fontawesome/brands/youtube'
      'link': 'https://www.youtube.com/c/MoonbeamNetwork'
      'name': 'YouTube'
    - 'icon': 'fontawesome/brands/github'
      'link': 'https://github.com/PureStake/moonbeam'
      'name': 'GitHub'
'google_analytics':
  - 'UA-135971059-6'
  - 'auto'
